server:
  port: 8081
  servlet:
    context-path: /activity
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/activity?serverTimezone=GMT%2B8&characterEncoding=utf8&useSSL=false
    username: root
    password: daixinbao
  freemarker:
    request-context-attribute: req #req访问request
    suffix: .html
    enabled: true
    template-loader-path: classpath:/templates/
    content-type: text/html
    charset: UTF-8
　  cache: false
